# this file is generated by:
#
#   script/generate extra_webrat_steps
#
# which uses features/step_definitions/webrat_steps.rb as a source
#
# So you will probably want to re-run the generator if the above file changes
<%- scoped_methods.each do |method| -%>

<%= method %>
<%- end -%>